Mathsoc office page created
MathSoc/mathsoc-website pull request #148
Opened 2023-03-31 20:59 UTC by angeladev333

Added and implemented the following files according to the styles of current pages:

- public\assets\css\pages\services\mathsoc-office.css
- public\assets\img\services\office.jpg
- public\assets\sass\pages\services\mathsoc-office.scss
- server\data\services\mathsoc-office.json
- views\pages\services\mathsoc-office.pug

2023-04-03 05:19 UTC, ad-world commented on views/pages/services/mathsoc-office.pug
> +                    p We provide Textbook Rentals, Board Game Rentals, Calculator Rentals, and equipment for our clubs and members!
can you add all the text like "We provide Textbook Rentals...." to the mathsoc-office.json file?

2023-04-03 05:21 UTC, ad-world commented on server/data/services/mathsoc-office.json
> +{
can you add this file to the data validation pipeline? otherwise, we won't be able to edit it through the cms.

2023-04-03 05:21 UTC, ad-world requested changes
left some comments

2023-04-03 21:36 UTC, angeladev333 commented
A clarification: this is a base for the mathsoc office page

2023-05-08 22:29 UTC, some-molasses commented
closing as part of inter-term cleanup :pensive:

2023-05-08 22:29 UTC, closed without merging