Create JSON editor for Volunteer page
MathSoc/mathsoc-website pull request #60
Opened 2023-01-15 22:28 UTC by ad-world

2023-01-15 22:34 UTC, ad-world commented
This PR includes a few things
- Creates a generalized JSON editor for CMS pages
- Creates filePath endpoints for reading and writing to nested data files within the data directory

The JSONEditor CDN stuff has been added to the admin-base layout, so adding the editor to any other page requires little work. Follow these steps:
1. Add the following code under the `append scripts` part of the pug file
```
script.
        document.addEventListener("DOMContentLoaded", function(event) { 
           // retrieve your server data, put it into a variable
            const sources = !{JSON.stringify(sources)}
            const editor = new Editor();
            // pass whatever data you want to show in the JSONeditor into the editor.useEditor function
            editor.useEditor(sources.volunteer);

            // create a button on the page, give it an id (doesn't matter what it is)
            document.getElementById([id-of-your-saving-button]).addEventListener("click", () => {
                editor.saveData('/api/data?path=[path-to-your-file]');
            })
        });
```
2. Add the following to the body of the pug file. It is very important that the id of the div is "jsoneditor"
`div(id="jsoneditor")`

3. Add a save button somewhere on the page. Make sure the id you gave the button is the same as the one in step 1.

2023-01-18 22:59 UTC, some-molasses requested changes

2023-01-18 22:59 UTC, some-molasses commented on public/assets/sass/pages/admin/get-involved/volunteer.scss
> +.save {
Can we put this in the main admin.scss file?  We'll need save buttons across the backend

2023-01-18 22:59 UTC, some-molasses commented on views/pages/admin/get-involved/volunteer.pug
> +    script.
We should put this script into its own file, rather than have it inline in the view file.

2023-01-18 22:59 UTC, some-molasses commented on server/types/validators.ts
> +const volunteerDataValidator: ExpressValidator = (req: Request, res: Response, next: NextFunction) => {
I think this validation pipeline could be abstracted out nicely, but that can come later!

2023-01-19 01:57 UTC, some-molasses commented on views/pages/admin/get-involved/volunteer.pug
> +    script.
nvm lol, I think we maybe could later but it'll take more work than is worth blocking this PR for

2023-01-19 02:00 UTC, some-molasses approved these changes
appppppppppppppppppppppppppppppppppppppppppppppppppppppppproved

2023-01-19 02:14 UTC, some-molasses approved these changes

2023-01-19 02:16 UTC, merged